apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: ejmadkins-pc-acm
  labels:
    geo: uk
    test: replace
  name: tenant-a
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: ejmadkins-pc-acm
  labels:
    geo: uk
    test: replace
  name: tenant-b
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: ejmadkins-pc-acm
  labels:
    geo: uk
    test: replace
  name: tenant-c
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    geo: uk
  name: tenant-sync
  namespace: tenant-a
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    geo: uk
  name: tenant-sync
  namespace: tenant-b
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    geo: uk
  name: tenant-sync
  namespace: tenant-c
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-impersonate
rules:
- apiGroups:
  - ""
  resourceNames:
  - darth@ejmadkins.altostrat.com
  resources:
  - users
  verbs:
  - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    geo: uk
  name: tenant-sync
  namespace: tenant-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-sync
subjects:
- kind: ServiceAccount
  name: ns-reconciler-tenant-a
  namespace: config-management-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    geo: uk
  name: tenant-sync
  namespace: tenant-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-sync
subjects:
- kind: ServiceAccount
  name: ns-reconciler-tenant-b
  namespace: config-management-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    geo: uk
  name: tenant-sync
  namespace: tenant-c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-sync
subjects:
- kind: ServiceAccount
  name: ns-reconciler-tenant-c
  namespace: config-management-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: darth@ejmadkins.altostrat.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-impersonate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-impersonate
subjects:
- kind: ServiceAccount
  name: connect-agent-sa
  namespace: gke-connect
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  labels:
    geo: uk
  name: repo-sync
  namespace: tenant-a
spec:
  git:
    auth: none
    branch: dev
    repo: https://github.com/ejmadkins/acm-multi-repo-tenant-a.git
  sourceFormat: unstructured
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  labels:
    geo: uk
  name: repo-sync
  namespace: tenant-b
spec:
  git:
    auth: none
    branch: dev
    repo: https://github.com/ejmadkins/acm-multi-repo-tenant-b.git
  sourceFormat: unstructured
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  labels:
    geo: uk
  name: repo-sync
  namespace: tenant-c
spec:
  git:
    auth: none
    branch: dev
    repo: https://github.com/ejmadkins/acm-multi-repo-tenant-c.git
  sourceFormat: unstructured
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPCapabilities
metadata:
  name: forbid-cap-net-raw
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    namespaces:
    - default
  parameters:
    requiredDropCapabilities:
    - NET_RAW
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-geo
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
  parameters:
    labels:
    - key: geo
---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: cnrmsa-dev-cluster-lon@ejmadkins-pc-acm.iam.gserviceaccount.com
  mode: cluster
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: tenant-a
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector: {}
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            k8s-namespace: kube-system
        podSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values: ["kube-dns","node-local-dns"]
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: tenant-b
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector: {}
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            k8s-namespace: kube-system
        podSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values: ["kube-dns","node-local-dns"]
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: tenant-c
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector: {}
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            k8s-namespace: kube-system
        podSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values: ["kube-dns","node-local-dns"]
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: cnrm-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: config-management-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: config-management-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: configconnector-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: default
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: gatekeeper-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: kube-node-lease
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: kube-public
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: kube-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    geo: uk
  name: resource-group-system
