resources:
- ../../../base/cluster
- ../../../tenants/tenant-a
- ../../../tenants/tenant-b

patches:
- target:
    kind: RepoSync
    name: repo-sync
  patch: |-
    - op: replace
      path: /spec/git/branch
      value: prod